SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE sp_Product_Delete
    @Id INT
AS
BEGIN
    SET NOCOUNT ON;
    SET QUOTED_IDENTIFIER ON;
    UPDATE Products SET IsDeleted = 1, UpdatedAt = GETUTCDATE() WHERE Id = @Id;
END
